version: '3'

services:
  backend:
    build: ./server
    image: event/backend
    container_name: backend
    restart: always
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    environment:
      NODE_ENV: '${NODE_ENV}'
      BACKEND_PORT: '${BACKEND_PORT}'
      BACKEND_ORIGIN: '${BACKEND_ORIGIN}'
      DATABASE_USERNAME: '${DATABASE_USERNAME}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      DATABASE_HOST: '${DATABASE_HOST}'
      DATABASE_PORT: '${DATABASE_PORT}'
      DATABASE_NAME: '${DATABASE_NAME}'
    networks:
      - event-network
    depends_on:
      - postgres
  frontend:
    build: ./web
    image: event/frontend
    container_name: frontend
    restart: always
    ports:
      - '${FRONTEND_PORT}:80'
    environment:
      NODE_ENV: '${NODE_ENV}'
      BACKEND_URL: '${BACKEND_URL}'
    networks:
      - event-network
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    networks:
      - event-network

networks:
  event-network:
