version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    environment:
      NODE_ENV: '${NODE_ENV}'
      BACKEND_PORT: '${BACKEND_PORT}'
      BACKEND_ORIGIN: '${BACKEND_ORIGIN}'
      DATABASE_USERNAME: '${DATABASE_USERNAME}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      DATABASE_HOST: '${DATABASE_HOST}'
      DATABASE_PORT: '${DATABASE_PORT}'
      DATABASE_NAME: '${DATABASE_NAME}'
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    networks:
      - base-network
    volumes:
      - './src:/app/src'
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    networks:
      - base-network

networks:
  base-network:
