version: '3'

services:
  frontend:
    build:
      context: .
      args:
        NODE_ENV: '${NODE_ENV}'
        BACKEND_URL: '${BACKEND_URL}'
    image: birthday/frontend
    container_name: frontend
    restart: always
    ports:
      - '${FRONTEND_PORT}:80'
